### PR TITLE
kernel/ and de/: Standardizing symbols for pointers and variables

### PR DESCRIPTION
**Pull request by carlosdaniel26**
I saw that the variable names and pointers don't look well self-explained, i know that we can't always have awesome variable names specially when its not something that we're going to see much times, this is the case of the  kstdio functions, something that we'll most of time just use instead of modify.

But since its an open source project, one of the beautiful things that open source give for us is tools/sources to learn, so for new contributors or even students that will use gramado as a example OS, is good have a good readability.

Seeing that i started to standardize some parts, if you have any sugestion or critic about some part of the code, im open to discuss about the best way to make the code more clear.

### CODE REVIEW

**Comment by nibblebits** [comment]
I don't believe it is neccessary to make these changes to the variables the originals seem fair and understandable, I agree with the comments being in English however.

**Comment by nibblebits** [comment]
I also agree with the "k" to be "kernel" all other variable changes seem unneccessary to me

**Comment by carlosdaniel26** [comment]
> I also agree with the "k" to be "kernel" all other variable changes seem unneccessary to me

I agree with you about `ptr_string` may be a unnecessarily explicit.

But must be a better way to call the character instead of `_char `

`ptr `is clearer than use just `p`

And maybe `ptr_character` can looks too explicit, but should be something more clear instead of just `cp`

**Comment by frednora** [comment]
> I saw that the variable names and pointers don't look well self-explained, i know that we can't always have awesome variable names specially when its not something that we're going to see much times, this is the case of the kstdio functions, something that we'll most of time just use instead of modify.
> 
> But since its an open source project, one of the beautiful things that open source give for us is tools/sources to learn, so for new contributors or even students that will use gramado as a example OS, is good have a good readability.
> 
> Seeing that i started to standardize some parts, if you have any sugestion or critic about some part of the code, im open to discuss about the best way to make the code more clear.

You are right. We need to standardize the whole project, The comments, the symbols for the functions, the symbols for the variables. >>>> But, we need to start, first of all, building the 'documentation' for these changes and all the changes will follow the rules in this documentation. Inside the kernel i will use some prefixes just like keXXXXX()  mmXXXXX() ... etc ... and outside the kernel each API will have their own rules. The major rule for me is that the lower layers are more flexible then the top layers. The upper layers needs to be more canonical because it is the user part of the system and the lower layers needs more flexibility because it needs to adapt with the changes in the hardware industry. So, let's do it ... let's create the rules ... and follow them all.

**Comment by frednora** [comment]
> I also agree with the "k" to be "kernel" all other variable changes seem unneccessary to me

hahahah ... this variable represents the entrypoint for the kernel image. I am using this routine to export some symbols from the kernel to a loadable ring0 kernel module. But right after the implementation of dynlinked kernel modules i will delete this routine.

**Comment by frednora** [comment]
> I saw that the variable names and pointers don't look well self-explained, i know that we can't always have awesome variable names specially when its not something that we're going to see much times, this is the case of the kstdio functions, something that we'll most of time just use instead of modify.
> 
> But since its an open source project, one of the beautiful things that open source give for us is tools/sources to learn, so for new contributors or even students that will use gramado as a example OS, is good have a good readability.
> 
> Seeing that i started to standardize some parts, if you have any sugestion or critic about some part of the code, im open to discuss about the best way to make the code more clear.
--------------
:)
The project does NOT have a documentation yet. All we have is a collection of design notes in docs/. We need to get all these notes and create a real documentation, explaing all the rules we want to follow. ... i just created a sub-folder called 'docs/cs/' for the 'coding style'. We can put there all the rules about symbols for functions and variables as well as all the rest of rules for coding inside the kernel base. https://github.com/gramado/kernel/tree/main/your/docs/cs

**Pull request closed without merging**
